doctrine_migrations:
  migrations_paths:
    'DoctrineMigrations': '%kernel.project_dir%/migrations'
  enable_profiler: true
  storage:
    table_storage:
      table_name: 'migration_versions'
      version_column_name: 'version'
      version_column_length: 191
      executed_at_column_name: 'executed_at'
      execution_time_column_name: 'execution_time'
  all_or_nothing: true
  check_database_platform: true
