# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: true

  # Configure the session storage and cookie settings
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax

  csrf_protection: true

  form:
    enabled: true

  validation:
    enabled: true
    enable_attributes: true

  # Configure assets
  assets:
    enabled: true

  # Configure the profiler
  profiler: { only_exceptions: false }

  # Configure the cache
  cache:
    app: cache.adapter.filesystem
    system: cache.adapter.system
    pools:
      my_cache_pool: { adapter: cache.adapter.filesystem }

  # Configure mailer
  mailer: { dsn: '%env(MAILER_DSN)%' }

  # Add PHP built-in server support
  router:
    utf8: true
    strict_requirements: ~

  default_locale: en
  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_hosts: '%env(TRUSTED_HOSTS)%'
